### ISSUE TITLE
Change mutually exclusive features to additive features

### ISSUE THREAD

**Issue by Chocorean** [mlemesle/rustemon#33]
Hello there, discovered your project today and went through your docs and examples - great work!
I noticed the two features for caching are mutually exclusive; this is a behavior to avoid and I wanted to share with you: (5min read)

https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification

Long story short: if two libs use rustemon with different features, what is happening?

Since you have already identified a default behavior, one suggestion is it could be removed as a feature, and adding the current non-default feature would override the default behavior.

What are your thoughts about it?

**Comment by mlemesle** [comment]
Hey @Chocorean,

Thanks for reaching out and for your kind comment on this project !
I apologize for taking so long to answer, I've been swamped in work.

We can do your solution I guess, but we could also just remove the features and just letting the user decide which manager he wants through `with_manager`. We should then decide for a default behavior which could be the in-memory one since it doesn't require the filesystem.

What do you think about it ?
I'm asking this to everyone posting an issue, do you want to do it yourself or you rather prefer me to do it ?
No worries, just let me know !

Thanks again for your contribution to Rustemon !
